/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/utils/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Background colors for personality themes
    'bg-amber-50',
    'bg-pink-100',
    'bg-red-50',
    'bg-gray-800',
    'bg-indigo-50',
    'bg-gray-600',
    'bg-yellow-100',
    'bg-purple-100',
    'bg-violet-100',
    'bg-gray-200',
    'bg-blue-50',
    // Header colors
    'bg-amber-600',
    'bg-pink-500',
    'bg-red-600',
    'bg-gray-900',
    'bg-indigo-600',
    'bg-gray-800',
    'bg-yellow-500',
    'bg-purple-600',
    'bg-violet-600',
    'bg-gray-500',
    'bg-blue-600',
    // Text colors
    'text-amber-700',
    'text-amber-900',
    'text-pink-600',
    'text-pink-800',
    'text-red-600',
    'text-red-800',
    'text-green-400',
    'text-green-300',
    'text-indigo-600',
    'text-indigo-800',
    'text-gray-300',
    'text-gray-200',
    'text-violet-600',
    'text-violet-800',
    'text-gray-600',
    'text-gray-700',
    'text-blue-600',
    'text-blue-800',
    // Border colors
    'border-amber-500',
    'border-pink-500',
    'border-red-500',
    'border-green-500',
    'border-indigo-500',
    'border-gray-500',
    'border-yellow-500',
    'border-purple-500',
    'border-violet-500',
    'border-blue-500',
    // Shadow colors
    'shadow-amber-500',
    'shadow-pink-500',
    'shadow-red-500',
    'shadow-green-500',
    'shadow-indigo-500',
    'shadow-gray-700',
    'shadow-yellow-500',
    'shadow-purple-500',
    'shadow-violet-500',
    'shadow-gray-500',
    'shadow-blue-500',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#1d4ed8',
      },
      keyframes: {
        'quantum-flicker': {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0.7', transform: 'scale(0.95)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'quantum-flicker': 'quantum-flicker 0.5s infinite alternate',
        'fade-in': 'fade-in 0.5s ease-in-out',
      },
    },
  },
  plugins: [],
};
